// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: lessons_tasks.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщения для уроков
type LessonCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonCreateRequest) Reset() {
	*x = LessonCreateRequest{}
	mi := &file_lessons_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonCreateRequest) ProtoMessage() {}

func (x *LessonCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonCreateRequest.ProtoReflect.Descriptor instead.
func (*LessonCreateRequest) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *LessonCreateRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *LessonCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type LessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonResponse) Reset() {
	*x = LessonResponse{}
	mi := &file_lessons_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonResponse) ProtoMessage() {}

func (x *LessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonResponse.ProtoReflect.Descriptor instead.
func (*LessonResponse) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *LessonResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LessonResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *LessonResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	mi := &file_lessons_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *UserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LessonsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lessons       []*LessonResponse      `protobuf:"bytes,1,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonsListResponse) Reset() {
	*x = LessonsListResponse{}
	mi := &file_lessons_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonsListResponse) ProtoMessage() {}

func (x *LessonsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonsListResponse.ProtoReflect.Descriptor instead.
func (*LessonsListResponse) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *LessonsListResponse) GetLessons() []*LessonResponse {
	if x != nil {
		return x.Lessons
	}
	return nil
}

// Сообщения для заданий
type TaskCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCreateRequest) Reset() {
	*x = TaskCreateRequest{}
	mi := &file_lessons_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCreateRequest) ProtoMessage() {}

func (x *TaskCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCreateRequest.ProtoReflect.Descriptor instead.
func (*TaskCreateRequest) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *TaskCreateRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *TaskCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_lessons_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *TaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TasksListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskResponse        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksListResponse) Reset() {
	*x = TasksListResponse{}
	mi := &file_lessons_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksListResponse) ProtoMessage() {}

func (x *TasksListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksListResponse.ProtoReflect.Descriptor instead.
func (*TasksListResponse) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *TasksListResponse) GetTasks() []*TaskResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// Сообщения для связи ученики-задания
type UserTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTaskRequest) Reset() {
	*x = UserTaskRequest{}
	mi := &file_lessons_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTaskRequest) ProtoMessage() {}

func (x *UserTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTaskRequest.ProtoReflect.Descriptor instead.
func (*UserTaskRequest) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{7}
}

func (x *UserTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UserTaskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_lessons_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserTasksListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskResponse        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTasksListResponse) Reset() {
	*x = UserTasksListResponse{}
	mi := &file_lessons_tasks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTasksListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTasksListResponse) ProtoMessage() {}

func (x *UserTasksListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTasksListResponse.ProtoReflect.Descriptor instead.
func (*UserTasksListResponse) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{9}
}

func (x *UserTasksListResponse) GetTasks() []*TaskResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// Общие сообщения
type CourseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseIdRequest) Reset() {
	*x = CourseIdRequest{}
	mi := &file_lessons_tasks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseIdRequest) ProtoMessage() {}

func (x *CourseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseIdRequest.ProtoReflect.Descriptor instead.
func (*CourseIdRequest) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{10}
}

func (x *CourseIdRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type LessonIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonIdRequest) Reset() {
	*x = LessonIdRequest{}
	mi := &file_lessons_tasks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonIdRequest) ProtoMessage() {}

func (x *LessonIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonIdRequest.ProtoReflect.Descriptor instead.
func (*LessonIdRequest) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{11}
}

func (x *LessonIdRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_lessons_tasks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lessons_tasks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_lessons_tasks_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_lessons_tasks_proto protoreflect.FileDescriptor

const file_lessons_tasks_proto_rawDesc = "" +
	"\n" +
	"\x13lessons_tasks.proto\x12\fclassroom.v1\"T\n" +
	"\x13LessonCreateRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"_\n" +
	"\x0eLessonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"(\n" +
	"\rUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x13LessonsListResponse\x126\n" +
	"\alessons\x18\x01 \x03(\v2\x1c.classroom.v1.LessonResponseR\alessons\"R\n" +
	"\x11TaskCreateRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"]\n" +
	"\fTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"E\n" +
	"\x11TasksListResponse\x120\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1a.classroom.v1.TaskResponseR\x05tasks\"C\n" +
	"\x0fUserTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"0\n" +
	"\x14CompleteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x15UserTasksListResponse\x120\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1a.classroom.v1.TaskResponseR\x05tasks\".\n" +
	"\x0fCourseIdRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\".\n" +
	"\x0fLessonIdRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x86\x02\n" +
	"\x0eLessonsService\x12O\n" +
	"\fCreateLesson\x12!.classroom.v1.LessonCreateRequest\x1a\x1c.classroom.v1.LessonResponse\x12V\n" +
	"\x12GetLessonsByCourse\x12\x1d.classroom.v1.CourseIdRequest\x1a!.classroom.v1.LessonsListResponse\x12K\n" +
	"\fDeleteLesson\x12\x1d.classroom.v1.LessonIdRequest\x1a\x1c.classroom.v1.DeleteResponse2\xdd\x02\n" +
	"\fTasksService\x12I\n" +
	"\n" +
	"CreateTask\x12\x1f.classroom.v1.TaskCreateRequest\x1a\x1a.classroom.v1.TaskResponse\x12R\n" +
	"\x10GetTasksByCourse\x12\x1d.classroom.v1.CourseIdRequest\x1a\x1f.classroom.v1.TasksListResponse\x12Q\n" +
	"\fCompleteTask\x12\x1d.classroom.v1.UserTaskRequest\x1a\".classroom.v1.CompleteTaskResponse\x12[\n" +
	"\x17GetCompletedTasksByUser\x12\x1b.classroom.v1.UserIdRequest\x1a#.classroom.v1.UserTasksListResponseBHZFgithub.com/moyamoyaradost/classroom-go/lessons-tasks-service/api/v1;v1b\x06proto3"

var (
	file_lessons_tasks_proto_rawDescOnce sync.Once
	file_lessons_tasks_proto_rawDescData []byte
)

func file_lessons_tasks_proto_rawDescGZIP() []byte {
	file_lessons_tasks_proto_rawDescOnce.Do(func() {
		file_lessons_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lessons_tasks_proto_rawDesc), len(file_lessons_tasks_proto_rawDesc)))
	})
	return file_lessons_tasks_proto_rawDescData
}

var file_lessons_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_lessons_tasks_proto_goTypes = []any{
	(*LessonCreateRequest)(nil),   // 0: classroom.v1.LessonCreateRequest
	(*LessonResponse)(nil),        // 1: classroom.v1.LessonResponse
	(*UserIdRequest)(nil),         // 2: classroom.v1.UserIdRequest
	(*LessonsListResponse)(nil),   // 3: classroom.v1.LessonsListResponse
	(*TaskCreateRequest)(nil),     // 4: classroom.v1.TaskCreateRequest
	(*TaskResponse)(nil),          // 5: classroom.v1.TaskResponse
	(*TasksListResponse)(nil),     // 6: classroom.v1.TasksListResponse
	(*UserTaskRequest)(nil),       // 7: classroom.v1.UserTaskRequest
	(*CompleteTaskResponse)(nil),  // 8: classroom.v1.CompleteTaskResponse
	(*UserTasksListResponse)(nil), // 9: classroom.v1.UserTasksListResponse
	(*CourseIdRequest)(nil),       // 10: classroom.v1.CourseIdRequest
	(*LessonIdRequest)(nil),       // 11: classroom.v1.LessonIdRequest
	(*DeleteResponse)(nil),        // 12: classroom.v1.DeleteResponse
}
var file_lessons_tasks_proto_depIdxs = []int32{
	1,  // 0: classroom.v1.LessonsListResponse.lessons:type_name -> classroom.v1.LessonResponse
	5,  // 1: classroom.v1.TasksListResponse.tasks:type_name -> classroom.v1.TaskResponse
	5,  // 2: classroom.v1.UserTasksListResponse.tasks:type_name -> classroom.v1.TaskResponse
	0,  // 3: classroom.v1.LessonsService.CreateLesson:input_type -> classroom.v1.LessonCreateRequest
	10, // 4: classroom.v1.LessonsService.GetLessonsByCourse:input_type -> classroom.v1.CourseIdRequest
	11, // 5: classroom.v1.LessonsService.DeleteLesson:input_type -> classroom.v1.LessonIdRequest
	4,  // 6: classroom.v1.TasksService.CreateTask:input_type -> classroom.v1.TaskCreateRequest
	10, // 7: classroom.v1.TasksService.GetTasksByCourse:input_type -> classroom.v1.CourseIdRequest
	7,  // 8: classroom.v1.TasksService.CompleteTask:input_type -> classroom.v1.UserTaskRequest
	2,  // 9: classroom.v1.TasksService.GetCompletedTasksByUser:input_type -> classroom.v1.UserIdRequest
	1,  // 10: classroom.v1.LessonsService.CreateLesson:output_type -> classroom.v1.LessonResponse
	3,  // 11: classroom.v1.LessonsService.GetLessonsByCourse:output_type -> classroom.v1.LessonsListResponse
	12, // 12: classroom.v1.LessonsService.DeleteLesson:output_type -> classroom.v1.DeleteResponse
	5,  // 13: classroom.v1.TasksService.CreateTask:output_type -> classroom.v1.TaskResponse
	6,  // 14: classroom.v1.TasksService.GetTasksByCourse:output_type -> classroom.v1.TasksListResponse
	8,  // 15: classroom.v1.TasksService.CompleteTask:output_type -> classroom.v1.CompleteTaskResponse
	9,  // 16: classroom.v1.TasksService.GetCompletedTasksByUser:output_type -> classroom.v1.UserTasksListResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_lessons_tasks_proto_init() }
func file_lessons_tasks_proto_init() {
	if File_lessons_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lessons_tasks_proto_rawDesc), len(file_lessons_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_lessons_tasks_proto_goTypes,
		DependencyIndexes: file_lessons_tasks_proto_depIdxs,
		MessageInfos:      file_lessons_tasks_proto_msgTypes,
	}.Build()
	File_lessons_tasks_proto = out.File
	file_lessons_tasks_proto_goTypes = nil
	file_lessons_tasks_proto_depIdxs = nil
}
